image: python:3.11-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONPATH: "$CI_PROJECT_DIR"

cache:
  paths:
    - .cache/pip
    - .venv/

stages:
  - lint
  - test

lint:
  stage: lint
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate || .venv/Scripts/activate
    - pip install --upgrade pip
    - pip install ruff
  script:
    - ruff check .

test:
  stage: test
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate || .venv/Scripts/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest
